apiVersion: v1
kind: Secret
metadata:
  name: social-media-client-secrets
  namespace: social-media-client
type: Opaque
data:
  CLIENT_API_ENDPOINT: aHR0cDovL3NvY2lhbC1tZWRpYS1hcGkuc29jaWFsLW1lZGlhLWFwaS5jbHVzdGVyLmxvY2FsOjg4MDAvYXBpLw==