apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-media-client.fullname" . }}
  namespace: {{ .Values.namespace}}
  labels:
    {{- include "social-media-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "social-media-client.selectorLabels" . | nindent 4 }}
